// Generated by scripts/generate-config.js
// Do not commit this file. Keep private.
window.FIREBASE_CONFIG = {
  "apiKey": "AIzaSyC6Cw-8GTNllDYx23FErkxr3J4h7QbUlQE",
  "authDomain": "fleurdelove-9926c.firebaseapp.com",
  "projectId": "fleurdelove-9926c",
  "storageBucket": "fleurdelove-9926c.firebasestorage.app",
  "messagingSenderId": "457357456144",
  "appId": "1:457357456144:web:7cc50a15f818fab96c6b95",
  "measurementId": "G-MJX2S4NBRB"
};
