const fs = require('fs');
const path = require('path');
require('dotenv').config({ path: path.join(process.cwd(), '.env') });

const outPath = path.join(process.cwd(), 'admin', 'firebase-config.js');

const cfg = {
  apiKey: process.env.FIREBASE_API_KEY || '',
  authDomain: process.env.FIREBASE_AUTH_DOMAIN || '',
  projectId: process.env.FIREBASE_PROJECT_ID || '',
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET || '',
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || '',
  appId: process.env.FIREBASE_APP_ID || '',
  measurementId: process.env.FIREBASE_MEASUREMENT_ID || ''
};

if (!cfg.apiKey) {
  console.error('FIREBASE_API_KEY is not set in .env. Aborting.');
  process.exit(1);
}

const content = `// Generated by scripts/generate-config.js
// Do not commit this file. Keep private.
window.FIREBASE_CONFIG = ${JSON.stringify(cfg, null, 2)};
`;

fs.writeFileSync(outPath, content, { encoding: 'utf8' });
console.log('Wrote', outPath);
